######## Stellar info ########
stellar:
  version: "1.5.1"

######## Sidebar ########
sidebar:
  logo:
    avatar: "[config.avatar](/about/)" # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: "[config.title](/)" # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: # '[btn.blog](/)'
    wiki: # '[btn.wiki](/wiki/)'
    friends: # '[友链](/friends/)'
    about: # '[关于](/about/)'
  # Sidebar widgets
  widgets:
    # default layout in home/wiki/categories/tags/archives pages
    default_layout: [friends]
    # Recent update
    recent:
      layout: recent
      rss: # /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.

######## Main ########
breadcrumb:
  home: config.title # config.title / config.author / home or custom content

######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 200
  # 分类颜色
  category_color:
    "新闻稿": "#DA0F47"
  # 文章许可协议
  license: "本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。"
  # 分享
  share: # [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    max_count: 5
    auto_cover: true # 如果没有封面就根据 tags 作为关键词搜索封面，开了此项将不会自动从文章中提取首张图片作为封面了。

######## Footer ########
footer:
  social:
    - title: RSS
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/25678f144c438.svg"/>'
      url: /atom.xml
    - title: GitHub
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/08a41b181ce68.svg"/>'
      url: https://github.com/Meta-Network
    # - title: Music
    #   icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/cf1ae151f9e83.svg"/>'
    #   url: /
    # - title: Comments
    #   icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/942ebbf1a4b91.svg"/>'
    #   url: /
  sitemap:
    # '博客':
    #   - '[近期](/)'
    #   - '[分类](/)'
    #   - '[标签](/)'
    #   - '[归档](/)'
    # '项目':
    #   - '[开源库](/)'
    #   - '[实用脚本](/)'
    # '社交':
    #   - '[友链](/)'
    #   - '[留言板](/)'
    #   - '[Spotify](/)'
    #   - '[Unsplash](/)'
    # '更多':
    #   - '[关于本站](/)'
    #   - '[GitHub](/)'
    #   - '[GitLab](/)'
  license: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  source: #'[GitHub](https://github.com/xaoxuu/hexo-theme-stellar)'
  more: # string or array (support markdown)
